// route:[
//     {
//         routeid:1,
//         routename:'阪急京都本線',
//         homename:[
//             {
//                 homeid:1,
//                 homename:'大阪梅田',
//                 timearray:[
//                     {
//                         trainsome:'準特急',
//                         traintime:'8:23'
//                     }
//                 ],
//             }
//         ]
//         delay:10
//     }
// ]